apiVersion: v1
kind: Pod
metadata:
  name: goapp-pod
  labels:
    env: prod
spec:
  containers:
  - image: graica10/goapp
    name: goapp-container
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: 
    - containerPort: 8080
      protocol: TCP
