apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs-sfs
spec:
  selector:
    matchLabels:
      app: nodejs-sfs
  serviceName: nodejs-sfs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-sfs
    spec:
      containers:
      - name: nodejs-sfs
        image: dangtong76/nodejs:sfs 
        ports:
        - name: http 
          containerPort: 8080 
        volumeMounts:
        - name: data 
          mountPath: /var/data
  volumeClaimTemplates:
  - metadata:
      name: data 
    spec:
      storageClassName: sc-standard-retain
      resources:
        requests:
          storage: 1Mi 
      accessModes:
      - ReadWriteOnce